# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "moment-2.24.0" = {
      name = "moment";
      packageName = "moment";
      version = "2.24.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.24.0.tgz";
        sha512 = "bV7f+6l2QigeBBZSM/6yTNq4P2fNpSWj/0e7jQcy87A8e7o2nAfP/34/2ky5Vw4B9S446EtIhodAzkFCcR4dQg==";
      };
    };
  };
  args = {
    name = "vscode-tlaplus";
    packageName = "vscode-tlaplus";
    version = "1.5.3";
    src = ./.;
    dependencies = [
      sources."moment-2.24.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "TLA+ language support";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}